### PR TITLE
Ok

### PR DESCRIPTION
**Pull request by sa283**
It ok

### CODE REVIEW

**Comment by Remruts** [comment]
Will test **very** seriously this **very** important feature later today.

**Comment by sa283** [comment]
Ok soory

**Comment by sa283** [comment]
Ok

**Comment by Remruts** [comment]
# It not ok

it_not_ok

In case you're not trolling, I didn't use godot's 2d physics gravity value for all my objects. The player character, for example, uses her own gravity. This is to have a finer control on the player's movement, though I think I didn't use it in the final game. 

Some objects do use it (like rigidbodies)! So changing that line wouldn't just change gameplay, but break stuff in an unintended way :)

**Pull request closed without merging**
